# Generated by Django 5.1.4 on 2024-12-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('total_spent', models.PositiveIntegerField(default=0)),
                ('discount', models.FloatField(default=0.0)),
            ],
        ),
    ]
